import { Router, type IRouter } from "express";
import { db } from "@workspace/db";
import { appUsersTable, userSessionsTable } from "@workspace/db";
import { eq, desc, count, ilike, or } from "drizzle-orm";
import { randomBytes } from "crypto";

const router: IRouter = Router();

const strip = (u: typeof appUsersTable.$inferSelect) => ({
  id: u.id, email: u.email, displayName: u.displayName,
  isActive: u.isActive, isEmailVerified: u.isEmailVerified,
  inviteCodeUsed: u.inviteCodeUsed,
  lastLoginAt: u.lastLoginAt instanceof Date ? u.lastLoginAt.toISOString() : u.lastLoginAt,
  createdAt:   u.createdAt   instanceof Date ? u.createdAt.toISOString()   : u.createdAt,
  updatedAt:   u.updatedAt   instanceof Date ? u.updatedAt.toISOString()   : u.updatedAt,
});

// List all app users
router.get("/admin/app-users", async (req, res): Promise<void> => {
  const page   = Math.max(1, Number(req.query.page)  || 1);
  const limit  = Math.min(100, Number(req.query.limit) || 50);
  const search = String(req.query.search || "").trim();
  const offset = (page - 1) * limit;

  const where = search
    ? or(ilike(appUsersTable.email, `%${search}%`), ilike(appUsersTable.displayName, `%${search}%`))
    : undefined;

  const [users, [{ total }]] = await Promise.all([
    db.select().from(appUsersTable)
      .where(where).orderBy(desc(appUsersTable.createdAt))
      .limit(limit).offset(offset),
    db.select({ total: count() }).from(appUsersTable).where(where),
  ]);

  res.json({ users: users.map(strip), total: Number(total) });
});

// Get single app user
router.get("/admin/app-users/:id", async (req, res): Promise<void> => {
  const [user] = await db.select().from(appUsersTable)
    .where(eq(appUsersTable.id, Number(req.params.id))).limit(1);
  if (!user) { res.status(404).json({ error: "User not found" }); return; }
  res.json(strip(user));
});

// Update app user (activate/deactivate, verify email, display name)
router.patch("/admin/app-users/:id", async (req, res): Promise<void> => {
  const id = Number(req.params.id);
  const { isActive, isEmailVerified, displayName } = req.body ?? {};
  const updates: Partial<typeof appUsersTable.$inferInsert> = {};

  if (typeof isActive === "boolean")        updates.isActive = isActive;
  if (typeof isEmailVerified === "boolean") {
    updates.isEmailVerified = isEmailVerified;
    if (isEmailVerified) updates.emailVerificationToken = null;
  }
  if (typeof displayName === "string") updates.displayName = displayName || null;

  if (Object.keys(updates).length === 0) {
    res.status(400).json({ error: "Nothing to update" }); return;
  }

  updates.updatedAt = new Date();
  const [updated] = await db.update(appUsersTable).set(updates)
    .where(eq(appUsersTable.id, id)).returning();
  if (!updated) { res.status(404).json({ error: "User not found" }); return; }
  res.json(strip(updated));
});

// Delete app user
router.delete("/admin/app-users/:id", async (req, res): Promise<void> => {
  const id = Number(req.params.id);
  const [deleted] = await db.delete(appUsersTable)
    .where(eq(appUsersTable.id, id)).returning();
  if (!deleted) { res.status(404).json({ error: "User not found" }); return; }
  res.json({ success: true });
});

// Revoke all sessions for a user
router.post("/admin/app-users/:id/revoke-sessions", async (req, res): Promise<void> => {
  await db.delete(userSessionsTable)
    .where(eq(userSessionsTable.userId, Number(req.params.id)));
  res.json({ success: true });
});

// Generate email verification token for user (admin resend)
router.post("/admin/app-users/:id/send-verification", async (req, res): Promise<void> => {
  const id = Number(req.params.id);
  const token = randomBytes(16).toString("hex");
  const [updated] = await db.update(appUsersTable)
    .set({ emailVerificationToken: token, updatedAt: new Date() })
    .where(eq(appUsersTable.id, id)).returning();
  if (!updated) { res.status(404).json({ error: "User not found" }); return; }
  req.log.info({ email: updated.email, token }, "Verification token generated by admin");
  res.json({ success: true, verificationToken: token, message: "Token generated (send via your email service)" });
});

export default router;
